name: Docker

on:
  push:
    branches:
      - "release"

jobs:
  # Push image to Docker Registry
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Dagger
      uses: dagger/dagger-action@v1
      with:
        install-only: true
    - name: Dagger
      run: |
        dagger init
        dagger new test -p plans/ai-demo
        dagger input yaml parameters -f app.yaml
        dagger input text kubeconfig ${KUBECONFIG}
        dagger input text push.target ghcr.io/${GHCR_USERNAME}/ai-demo
        dagger input text push.auth.username ${GHCR_USERNAME}
        dagger input secret push.auth.secret ${GITHUB_TOKEN}
        dagger up
