name: Docker

on:
  push:
    branches:
      - "release"

jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      GITHUB_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Dagger
      uses: dagger/dagger-action@v1
      with:
        install-only: true
    - name: Dagger Setup
      run: |
        dagger init
        dagger new test -p plans/ai-demo
        dagger input yaml parameters -f app.yaml
        echo $KUBECONFIG > kubeconfig
        dagger input text kubeconfig -f ./kubeconfig
        dagger input text push.target ghcr.io/$GITHUB_USERNAME/ai-demo
        dagger input text push.auth.username $GITHUB_USERNAME
        dagger input secret push.auth.secret $GITHUB_TOKEN
    - name: Dagger Up
      run: |
        dagger up
